name: PHPUnit

on: push

jobs:

  phpunit:

    name: Run PHPUnit

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout code

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extension: ctype, bcmath, fileinfo, json, mbstring, openssl, pdo, tokenizer, xml
          coverage: none

      - name: Install Composer dependencies
        run: |
          composer install -n --prefer-dist
          cp .env.example .env.ci
          php artisan key:generate

      - name: Run tests
        run: ./vendor/bin/phpunit
